apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch
  labels:
    app: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - image: kkos2display/elasticsearch:1.7.1-kff-0.1.0
        imagePullPolicy: Always
        name: elasticsearch
        ports:
        - name: main-port
          containerPort: 9200
        volumeMounts:
          - name: esdata
            mountPath: /var/lib/elasticsearch
        readinessProbe:
          httpGet:
            path: /_cluster/health
            port: main-port
          initialDelaySeconds: 5
        livenessProbe:
          httpGet:
            path: /_cluster/health?local=true
            port: main-port
          initialDelaySeconds: 20
      initContainers:
        - name: fix-permissions
          image: kkos2display/elasticsearch:1.7.1-kff-0.1.0
          command: ["sh", "-c", "chown -R elasticsearch:elasticsearch /var/lib/elasticsearch"]
          volumeMounts:
            - name: esdata
              mountPath: /var/lib/elasticsearch
      volumes:
        - name: esdata
          persistentVolumeClaim:
            claimName: esdata-claim
