apiVersion: v1
kind: ConfigMap
metadata:
  name: search-initial-config
data:
  apikeys.json: |
    {
      "795359dd2c81fa41af67faa2f9adbd32": {
        "name": "IK3",
        "expire": 300,
        "indexes": [
          "e7df7cd2ca07f4f1ab415d457a6e1c13"
        ],
        "access": "rw"
      },
      "88cfd4b277f3f8b6c7c15d7a84784067": {
        "name": "Share",
        "expire": 300,
        "indexes": [
          "itkdevshare",
          "bibshare"
        ],
        "access": "rw"
      }
    }
  config.json: |
    {
      "port": 3010,
      "secret": "MySuperSecret",
      "admin": {
        "username": "admin",
        "password": "admin"
      },
      "logs": {
        "all": "logs/messages.log",
        "info": "logs/info.log",
        "error": "logs/error.log",
        "debug": "logs/debug.log",
        "socket": "logs/socket.log"
      },
      "search": {
        "hosts": [ "elasticsearch:9200" ],
        "mappings": "mappings.json"
      },
      "apikeys": "apikeys.json",
      "sentryUrl": "https://xxx:xxx@app.getsentry.com/xxx"
    }
  mappings.json: |
    {
      "e7df7cd2ca07f4f1ab415d457a6e1c13": {
        "name": "IK3",
        "tag": "private",
        "fields": [
          {
            "field": "title",
            "type": "string",
            "language": "da",
            "country": "DK",
            "default_analyzer": "string_index",
            "default_indexer": "analyzed",
            "sort": true,
            "indexable": true,
            "raw": false
          },
          {
            "type": "string",
            "country": "DK",
            "language": "da",
            "default_analyzer": "string_index",
            "default_indexer": "analyzed",
            "sort": true,
            "indexable": true,
            "raw": false,
            "geopoint": false,
            "field": "name"
          }
        ],
        "dates": [ "created_at", "updated_at" ]
      },
      "88cfd4b277f3f8b6c7c15d7a84784067": {
        "name": "Share",
        "tag": "private",
        "fields": [
          {
            "field": "title",
            "type": "string",
            "language": "da",
            "country": "DK",
            "default_analyzer": "string_index",
            "default_indexer": "analyzed",
            "sort": true,
            "indexable": true,
            "raw": false
          },
          {
            "type": "string",
            "country": "DK",
            "language": "da",
            "default_analyzer": "string_index",
            "default_indexer": "analyzed",
            "sort": true,
            "indexable": true,
            "raw": false,
            "geopoint": false,
            "field": "name"
          }
        ],
        "dates": [ "created_at", "updated_at" ]
      }
    }
