version: "3.2"
services:

  admin-nginx:
    image: eu.gcr.io/os2display-bbs/os2display-bbs/admin-nginx:bbs-0.0.2
    ports:
      - 80
    # We need search and middleware to be resolvable before starting.
    volumes:
      - admin-release:/var/www
      - symfony-cache:/var/www/admin/app/cache
      - admin-uploads:/var/www/admin/web/uploads
    depends_on:
      - middleware
      - search
      - admin_release
    environment:
      VIRTUAL_HOST: admin.os2display.docker
      APP_ENV: "dev"
      APP_DEBUG: "1"
    networks:
      - backend

  admin-php:
    image: eu.gcr.io/os2display-bbs/os2display-bbs/admin-php:bbs-0.0.2
    depends_on:
      - admin_release
    volumes:
      - admin-release:/var/www
      - admin-uploads:/var/www/admin/web/uploads
      - symfony-cache:/var/www/admin/app/cache
      - ./development/config/parameters.yml:/var/www/admin/app/config/parameters.yml
      - ./development/scripts:/opt/development/scripts
    environment:
      # PHPstorm needs this to work with xdebug.
      PHP_IDE_CONFIG: "serverName=admin.os2display.docker"
      APP_ENV: "dev"
      APP_DEBUG: "1"
    networks:
      - backend

  admin-cron:
    image: eu.gcr.io/os2display-bbs/os2display-bbs/admin-php:bbs-0.0.2
    depends_on:
      - admin_release
    volumes:
      - admin-release:/var/www
      - admin-uploads:/var/www/admin/web/uploads
      - symfony-cache:/var/www/admin/app/cache
      - ./development/config/parameters.yml:/var/www/admin/app/config/parameters.yml
      - ./development/scripts:/opt/development/scripts
    environment:
      # The crontab picks this up and passes it to Symfony.
      APP_ENV: "dev"
      APP_DEBUG: "1"
    networks:
      - backend
    command: jobber-entrypoint.sh

  # Contains the latest source-release.
  # This service only has any effect when the admin-release volume is empty.
  # Ie. introduce an empty admin-release: volume in a docker-compose.override.yml.
  admin_release:
    image: eu.gcr.io/os2display-bbs/os2display-bbs/admin-release:bbs-build-7
    volumes:
      - admin-release:/release
    networks:
      - backend
    command: /opt/init-copy-source.sh

  elasticsearch:
    image: eu.gcr.io/os2display-bbs/os2display-bbs/elasticsearch:1.7.1-bbs-0.0.1
    networks:
      - backend
    volumes:
      - es-data:/var/lib/elasticsearch

  search:
    image: eu.gcr.io/os2display-bbs/os2display-bbs/search:2.1.10-docker-compatibility-2-bbs-0.0.2
    ports:
      - 3010
    volumes:
      # Mount in a log-tailer that will output our logs to standard out
      - './images/search/tools/log-stream-service.sh:/etc/my_init.d/99_log-tailer:ro'
    environment:
      VIRTUAL_HOST: search.os2display.docker
    depends_on:
      - elasticsearch
    networks:
      - backend

  redis:
    image: eu.gcr.io/os2display-bbs/os2display-bbs/redis:4.0.9-bbs-0.0.1
    networks:
      - backend

  middleware:
    image: eu.gcr.io/os2display-bbs/os2display-bbs/middleware:5.0.2-console-json-logging-2-bbs-0.0.2
    ports:
      - 3020
    networks:
      - backend
    environment:
      VIRTUAL_HOST: middleware.os2display.docker
    depends_on:
      - redis
    volumes:
      # Mount in a log-tailer that will output our logs to standard out
      - './images/middleware/tools/log-stream-service.sh:/etc/my_init.d/99_log-tailer:ro'

  screen:
    image: eu.gcr.io/os2display-bbs/os2display-bbs/screen:5.0.3-bbs-0.0.2
    ports:
      - 80
    environment:
      VIRTUAL_HOST: screen.os2display.docker
    networks:
      - backend
    # We proxy these so need them to exist.
    depends_on:
      - middleware
      - search

  admin-db:
    image: mariadb:10.3
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: os2display
      MYSQL_USER: os2display
      MYSQL_PASSWORD: os2display
    volumes:
      - db-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    networks:
      - backend
    environment:
      VIRTUAL_HOST: mail.os2display.docker
      VIRTUAL_PORT: 8025


networks:
  backend:

volumes:
  es-data:
  db-data:
  admin-uploads:
  symfony-cache:
  admin-release:
    driver_opts:
      type: none
      device: $PWD/development
      o: bind

