version: "3.2"
services:

  admin_nginx:
    image: os2display/admin-nginx
    ports:
      - 80
    # We need search_node and middleware to be resolvable before starting.
    volumes:
      - admin-release:/var/www/admin
      - symfony-cache:/var/www/admin/app/cache
      - admin-uploads:/var/www/admin/web/uploads
    depends_on:
      - middleware
      - search_node
      - admin_release
    environment:
      VIRTUAL_HOST: admin.os2display.docker
    networks:
      - backend

  admin_php:
    image: os2display/admin-php
    depends_on:
      - admin_release
    volumes:
      - admin-release:/var/www/admin
      - admin-uploads:/var/www/admin/web/uploads
      - symfony-cache:/var/www/admin/app/cache
      - ./development/config/parameters.yml:/var/www/admin/app/config/parameters.yml
      - ./development/scripts:/opt/development/scripts
    networks:
      - backend

  admin_release:
    image: os2display/admin-release
    volumes:
      - admin-release:/var/www/admin
    networks:
      - backend

  elasticsearch:
    image: os2display/elasticsearch
    networks:
      - backend
    volumes:
      - es-data:/var/lib/elasticsearch

  search_node:
    image: os2display/search_node
    ports:
      - 3010
    volumes:
      # Mount in a log-tailer that will output our logs to standard out
      - './images/search_node/tools/log-stream-service.sh:/etc/my_init.d/99_log-tailer:ro'
    environment:
      VIRTUAL_HOST: search.os2display.docker
    depends_on:
      - elasticsearch
    networks:
      - backend

  redis:
    image: os2display/redis
    networks:
      - backend

  middleware:
    image: os2display/middleware
    ports:
      - 3020
    networks:
      - backend
    environment:
      VIRTUAL_HOST: middleware.os2display.docker
    depends_on:
      - redis
    volumes:
      # Mount in a log-tailer that will output our logs to standard out
      - './images/middleware/tools/log-stream-service.sh:/etc/my_init.d/99_log-tailer:ro'

  admin_db:
    image: mariadb:10
    networks:
      - backend
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: os2display
      MYSQL_USER: os2display
      MYSQL_PASSWORD: os2display
    volumes:
      - db-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

  screen:
    image: os2display/screen
    ports:
      - 80
    environment:
      VIRTUAL_HOST: screen.os2display.docker
    networks:
      - backend
    # We proxy these so need them to exist.
    depends_on:
      - middleware
      - search_node

networks:
  backend:

volumes:
  es-data:
  db-data:
  admin-uploads:
  symfony-cache:
  admin-release:
    driver_opts:
      type: none
      device: $PWD/development/admin
      o: bind
