apiVersion: apps/v1
kind: Deployment
metadata:
  name: middleware
  labels:
    app: middleware
spec:
  replicas: 1
  selector:
    matchLabels:
      app: middleware
  template:
    metadata:
      labels:
        app: middleware
    spec:
      containers:
      - image: kkos2display/middleware:5.0.2-console-json-logging-2-kff-0.1.0
        imagePullPolicy: Always
        name: middleware
        ports:
        - name: main-port
          containerPort: 3020
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", 'rm -f /home/app/middleware/config.json && ln -s /middleware-config/config.json /home/app/middleware/config.json && rm -f /home/app/middleware/apikeys.json && ln -s /middleware-config/apikeys.json /home/app/middleware/apikeys.json']
        volumeMounts:
          - name: middleware-config
            mountPath:  /middleware-config

      volumes:
        - name: middleware-config
          configMap:
            name: middleware-config
