apiVersion: apps/v1
kind: Deployment
metadata:
  name: screen
  labels:
    app: screen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: screen
  template:
    metadata:
      labels:
        app: screen
    spec:
      containers:
      - image: kkos2display/screen
        imagePullPolicy: Always
        name: screen
        volumeMounts:
        - name: screen-config
          mountPath: /var/www/screen/app/config.js
          subPath: config.js
        ports:
        - name: main-port
          containerPort: 80
      volumes:
        - name: screen-config
          configMap:
            name: screen-config
