apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: kkos2display/redis:4.0.9-kff-0.1.0
        imagePullPolicy: Always
        name: redis
        ports:
        - name: main-port
          containerPort: 6379
