apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - image: eu.gcr.io/os2display-bbs/os2display-bbs/redis:4.0.9-bbs-0.0.1
        imagePullPolicy: Always
        name: redis
        ports:
        - name: main-port
          containerPort: 6379
