apiVersion: v1
kind: ConfigMap
metadata:
  name: screen-config
data:
  config.js: |
    /**
     * Sets up the config for the app.
     */
    window.config = {
      // Used to activate screen (rest API) and load resources.
      "resource": {
        "server": "//screen.kkos2display.dk/",
        "uri": 'proxy'
      },
      // Used by web-socket.
      "ws": {
        "server": "https://screen.kkos2display.dk/"
      },
      // API key to use.
      "apikey": "79fce1c5fae2b9eeaa4c0bf16bf33a18",
      // If cookie is secure it's only send over https.
      "cookie": {
        "secure": true
      },
      // Display debug messages.
      "debug": false,
      // Software version.
      "version": "test",
      // itkLog configuration.
      "itkLog": {
        "version": "1",
        "errorCallback": null,
        "logToConsole": true,
        "logLevel": "all"
      },
      // Fallback image url, (null = default), else set to "assets/images/fallback_override.png" and add the image
      fallback_image: null
    };
