apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: screen-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    certmanager.k8s.io/issuer: letsencrypt-prod
spec:
  rules:
    - host: screen.kkos2display.dk
      http:
        paths:
          - backend:
              serviceName: screen
              servicePort: main-port
            path: /
  tls:
    - hosts:
        - screen.kkos2display.dk
      secretName: screen-ingress-cert # cert-manager will populate this.
