apiVersion: v1
kind: ConfigMap
metadata:
  name: search-config
data:
  apikeys.json: |
    {
      "a0e2c343e8c73ca2dda0728028868b4d": {
        "name": "AdminSearchIndex",
        "expire": 300,
        "indexes": [
          "7ce1e3e030204ac40182399be05e5c4b"
        ],
        "access": "rw"
      }
    }
  config.json: |
    {
      "port": 3010,
      "secret": "3f012b89f876425533ea2383b6de7094",
      "admin": {
        "username": "admin",
        "password": "IkeS4ohSha"
      },
      "logs": {
        "all": "logs/messages.log",
        "info": "logs/info.log",
        "error": "logs/error.log",
        "debug": "logs/debug.log",
        "socket": "logs/socket.log"
      },
      "search": {
        "hosts": [ "elasticsearch:9200" ],
        "mappings": "mappings.json"
      },
      "apikeys": "apikeys.json",
      "sentryUrl": "https://xxx:xxx@app.getsentry.com/xxx"
    }
  mappings.json: |
    {
      "7ce1e3e030204ac40182399be05e5c4b": {
        "name": "AdminSearchIndex",
        "tag": "private",
        "fields": [
        {
          "field": "title",
          "type": "string",
          "language": "da",
          "country": "DK",
          "default_analyzer": "string_index",
          "default_indexer": "analyzed",
          "sort": true,
          "indexable": true,
          "raw": false
        },
        {
          "type": "string",
          "country": "DK",
          "language": "da",
          "default_analyzer": "string_index",
          "default_indexer": "analyzed",
          "sort": true,
          "indexable": true,
          "raw": false,
          "geopoint": false,
          "field": "name"
        }
        ],
        "dates": [ "created_at", "updated_at" ]
      }
    }
