apiVersion: v1
kind: ConfigMap
metadata:
  name: search-config
data:
  apikeys.json: |
    {
      "<insert-search-api-key-here>": {
        "name": "AdminSearchIndex",
        "expire": 300,
        "indexes": [
          "<insert-search-index-id-here>"
        ],
        "access": "rw"
      }
    }
  config.json: |
    {
      "port": 3010,
      "secret": "<insert-secret-here>",
      "admin": {
        "username": "<insert-admin-username-here>",
        "password": "<insert-admin-password-here>"
      },
      "logs": {
        "all": "logs/messages.log",
        "info": "logs/info.log",
        "error": "logs/error.log",
        "debug": "logs/debug.log",
        "socket": "logs/socket.log"
      },
      "search": {
        "hosts": [ "elasticsearch:9200" ],
        "mappings": "mappings.json"
      },
      "apikeys": "apikeys.json",
      "sentryUrl": "https://xxx:xxx@app.getsentry.com/xxx"
    }
  mappings.json: |
    {
      "<insert-search-index-id-here>": {
        "name": "AdminSearchIndex",
        "tag": "private",
        "fields": [
          {
            "field": "title",
            "type": "string",
            "language": "da",
            "country": "DK",
            "default_analyzer": "string_index",
            "default_indexer": "analyzed",
            "sort": true,
            "indexable": true,
            "raw": false
          },
          {
            "type": "string",
            "country": "DK",
            "language": "da",
            "default_analyzer": "string_index",
            "default_indexer": "analyzed",
            "sort": true,
            "indexable": true,
            "raw": false,
            "geopoint": false,
            "field": "name"
          }
        ],
        "dates": [ "created_at", "updated_at" ]
      }
    }
