apiVersion: v1
kind: ConfigMap
metadata:
  name: middleware-config
data:
  apikeys.json: |
    {
      "79fce1c5fae2b9eeaa4c0bf16bf33a18": {
        "name": "AdminMiddleware",
        "backend": "http://admin",
        "expire": 300
      }
    }
  config.json: |
    {
      "port": 3020,
      "secret": "5d25886221c75f2bccd6e126d8d8ccd9",
      "logs": {
        "all": "logs/messages.log",
        "info": "logs/info.log",
        "error": "logs/error.log",
        "debug": "logs/debug.log",
        "exception": "logs/exceptions.log",
        "socket": "logs/socket.log"
      },
      "admin": {
        "username": "admin",
        "password": "thueCee4sa"
      },
      "cache": {
        "port": "6379",
        "host": "redis",
        "auth": null,
        "db": 0
      },
      "apikeys": "apikeys.json"
    }
