apiVersion: v1
kind: ConfigMap
metadata:
  name: middleware-initial-config
data:
  apikeys.json: |
    {
      "<insert-middleware-apikey-here>": {
        "name": "AdminMiddleware",
        "backend": "http://admin",
        "expire": 300
      }
    }
  config.json: |
    {
      "port": 3020,
      "secret": "<insert-secret-here>",
      "logs": {
        "all": "logs/messages.log",
        "info": "logs/info.log",
        "error": "logs/error.log",
        "debug": "logs/debug.log",
        "exception": "logs/exceptions.log",
        "socket": "logs/socket.log"
      },
      "admin": {
        "username": "admin",
        "password": "<insert-admin-password-here>"
      },
      "cache": {
        "port": "6379",
        "host": "redis",
        "auth": null,
        "db": 0
      },
      "apikeys": "apikeys.json"
    }
