apiVersion: v1
kind: ConfigMap
metadata:
  name: middleware-config
data:
  apikeys.json: |
    {
      "<insert-middleware-apikey-here>": {
        "name": "AdminMiddleware",
        "backend": "http://admin",
        "expire": 300
      }
    }
  config.json: |
    {
      "port": 3020,
      "secret": "<insert-middleware-secret-here>",
      "logs": {
        "mode": "console-json"
      },
      "admin": {
        "username": "<insert-middleware-username-here>",
        "password": "<insert-middleware-password-here>"
      },
      "cache": {
        "port": "6379",
        "host": "redis",
        "auth": null,
        "db": 0
      },
      "apikeys": "apikeys.json"
    }
